export const FORM_I18N_KEYS = {
  TITLE: 'form.title',
  GREETING: 'form.greeting',
  RESUME: 'form.resume',
  RESUME_LINK: 'form.resume.link',
  NAME_LABEL: 'form.name.label',
  EMAIL_LABEL: 'form.email.label',
  SUBJECT_LABEL: 'form.subject.label',
  MESSAGE_LABEL: 'form.message.label',
  SUBMIT: 'form.submit',
  SUBMITTING: 'form.submitting',
  VALIDATION_NAME_MIN: 'form.validation.name.min',
  VALIDATION_NAME_MAX: 'form.validation.name.max',
  VALIDATION_EMAIL_REQUIRED: 'form.validation.email.required',
  VALIDATION_EMAIL_INVALID: 'form.validation.email.invalid',
  VALIDATION_SUBJECT_REQUIRED: 'form.validation.subject.required',
  VALIDATION_SUBJECT_MIN: 'form.validation.subject.min',
  VALIDATION_SUBJECT_MAX: 'form.validation.subject.max',
  VALIDATION_MESSAGE_REQUIRED: 'form.validation.message.required',
  VALIDATION_MESSAGE_MIN: 'form.validation.message.min',
  VALIDATION_MESSAGE_MAX: 'form.validation.message.max',
  TOAST_SUCCESS: 'toast.form.success',
  TOAST_NETWORK_ERROR: 'toast.form.network.error',
} as const;
